### ISSUE TITLE
Regex are mangled

### ISSUE THREAD

**Issue by aggsol** [flplv/vala-uncrustify#4]
With the current config spaces are inserted to RegEx.

Input

```cs
void main()
{
	Regex r = /^\s*(?P<parameter>.*)\s*=\s*(?P<value>.*)\s*$/;
	MatchInfo info;
	if(r.match(the_string, 0, out info)) {
		var parameter = info.fetch_named("parameter");
		var value = info.fetch_named("value");
}
}
```

Output:

```cs
void main()
{
  Regex r = / ^ \ s * (?P<parameter> .*) \ s *= \ s * (?P<value> .*) \ s * $ /;
  MatchInfo info;
  if (r.match(the_string, 0, out info)) {
    var parameter = info.fetch_named("parameter");
    var value = info.fetch_named("value");
  }
}
```

Expected behaviour:

Regex are not changed.
Tested with Uncrustify_d-0.70.1-253-86143624 (current master)

**Comment by flplv** [comment]
Thank you, will have a look when I have time.

**Comment by aggsol** [comment]
One culprit is `sp_arith=force `. My current workaround is to wrap the Regex in a string. I currently see no other way.

**Comment by aggsol** [comment]
Turns out my workaround is the best way recommended by uncrustify see https://github.com/uncrustify/uncrustify/issues/2687#issuecomment-600739512
